//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrushFX_PaintingCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContactInfo
    {
        [Required]
        [StringLength(50,ErrorMessage ="The name you entered is too long.")]
        public string Username { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "The email address you entered is too long.")]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(1000, ErrorMessage = "The message you entered is too long.")]
        public string Message { get; set; }
        [Key]
        public int ContactKey { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber,ErrorMessage = "Please enter a valid phone number format.")]
        public string PhoneNumber { get; set; }
    }
}
