//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrushFX_PaintingCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SecureUser
    {
        [Required]
        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter in a valid email address")]
        public string EmailAddress { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password,ErrorMessage = "Please enter in a valid password")]
        public string PasswordHash { get; set; }
        [Key]
        public int UserKey { get; set; }
    }
}
